### ISSUE TITLE
undefined title when not adding a sidebar.yaml to folder

### ISSUE THREAD

**Issue by svict4** [acrobit/docusaurus-plugin-auto-sidebars#4]
When I create a folder, add a markdown file in it, and don't define a `sidebar.yaml` it will error, when using the plugin out of the box

    TypeError: Cannot read property 'title' of undefined
        at \node_modules\docusaurus-plugin-auto-sidebars\lib\generator.js:26:24

You might need a better way than just [making it an empty string](https://github.com/acrobit/docusaurus-plugin-auto-sidebars/blob/master/src/utils/sidebarsMetadataLoader.ts#L23)

**Comment by ghominejad** [comment]
Hi @svict4, Yes and I've just fixed it in `v1.0.6`

Thanks a lot
